import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from '../lib/query'
import Product from '../components/Products'
import { Gallery } from '../styles/Gallery'

export default function Home() {

  const [results]=useQuery({query:PRODUCT_QUERY})
  console.log(results)
  const {data, fetching, error}= results

if (fetching)return <p>Loading..</p>
if (error)return <p>Oh No.....{error.data}</p>

const products = data.products.data
console.log(products)

  return (
    <div className={styles.container}>
      <Head>
        <title>Style Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery>
      {products.map((product)=>(
       <Product  key={product.attributes.Slug} product={product} /> 
      ))}
      </Gallery>

      </main>
    </div>
  )
}
